spring:
    application:
        name: auth-service


    datasource:
        url: jdbc:postgresql://localhost:5001/auth_db
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
          ddl-auto: update # Em Produção usamos 'validate' ou 'none' (com Flyway)
        show-sql: true
        properties:
            hibernate:
                format_sql:true
        open-in-view: false 

    # Configurações do JWT (Custom)
    security:
        jwt:
            secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 3600000
            refresh-token: 
                expiration: 86400000

server:
    port: 8081
            